# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install any necessary dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container
COPY . .

# Expose the port streamlit will run on
EXPOSE 8501

# Default command to run the streamlit app
ENTRYPOINT [ "streamlit", "run"]

# Command to run app
CMD [ "app.py" ]