services:
    elasticsearch-init:
        image: alpine:latest
        container_name: elasticsearch-init
        volumes:
            - /tmp/elasticsearch_data:/usr/share/elasticsearch/data
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        deploy:
            resources:
                limits:
                    memory: 128M
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
        container_name: elasticsearch
        volumes:
            - /tmp/elasticsearch_data:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        ports:
            - "9200:9200"
            - "9300:9300"
    ollama:
        image: ollama/ollama
        container_name: ollama
        volumes:
            - ollama:/root/.ollama
        ports:
            - "11434:11434"
        deploy:
            resources:
                limits:
                    memory: 6G

volumes:
    ollama:
        name: ollama